// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVXJ8sjtn9QBLRKRMYDGZN8M6DV8MP1kw',
    appId: '1:147859431162:web:c060e243c801a981e0f343',
    messagingSenderId: '147859431162',
    projectId: 'tpflutterchemlal',
    authDomain: 'tpflutterchemlal.firebaseapp.com',
    storageBucket: 'tpflutterchemlal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoL914iJlC05wG9bWtjyC3Vxr9T8fDgjg',
    appId: '1:147859431162:android:76f0a9ff3c0e0171e0f343',
    messagingSenderId: '147859431162',
    projectId: 'tpflutterchemlal',
    storageBucket: 'tpflutterchemlal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj9vFhaQwOFhlCOpCYkNYOcCqUMHp2Jls',
    appId: '1:147859431162:ios:16650a62f2053e24e0f343',
    messagingSenderId: '147859431162',
    projectId: 'tpflutterchemlal',
    storageBucket: 'tpflutterchemlal.firebasestorage.app',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj9vFhaQwOFhlCOpCYkNYOcCqUMHp2Jls',
    appId: '1:147859431162:ios:16650a62f2053e24e0f343',
    messagingSenderId: '147859431162',
    projectId: 'tpflutterchemlal',
    storageBucket: 'tpflutterchemlal.firebasestorage.app',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVXJ8sjtn9QBLRKRMYDGZN8M6DV8MP1kw',
    appId: '1:147859431162:web:dd913689b99382ace0f343',
    messagingSenderId: '147859431162',
    projectId: 'tpflutterchemlal',
    authDomain: 'tpflutterchemlal.firebaseapp.com',
    storageBucket: 'tpflutterchemlal.firebasestorage.app',
  );
}
